package auction.control;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import auction.model.Auction;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class auctionViewController {
	@FXML
	private Button closeAuctionButton;
	@FXML
	private Button addBidderButton;
	@FXML
	private Label StatusLabel;
	@FXML
	private Label endTimeLabel;
	@FXML
	private Label remainingTimeLabel;
	@FXML
	private Label currentBidLabel;
	@FXML
	private Label titleLabel;
	

	public auctionViewController(Auction auction) {
	}
	// Event Listener on Button[#closeAuctionButton].onAction
	@FXML
	public void closeAuction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addBidderButton].onAction
	@FXML
	public void addBidder(ActionEvent event) {
		// TODO Autogenerated
	}
}
