package auction.control;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class bidderViewController {
	@FXML
	private Label auctionItemLabel;
	@FXML
	private Button placeBidButton;
	@FXML
	private Label messageLabel;
	@FXML
	private Button logoutButton;

	// Event Listener on Button[#placeBidButton].onAction
	@FXML
	public void placeBid(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#logoutButton].onAction
	@FXML
	public void logout(ActionEvent event) {
		// TODO Autogenerated
	}
}
