package auction.control;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

import javafx.scene.layout.BorderPane;

public class loginViewController {
	@FXML
	private BorderPane root;
	@FXML
	private TextField username;
	@FXML
	private PasswordField password;

	// Event Listener on Button.onAction
	@FXML
	public void login(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void cancel(ActionEvent event) {
		// TODO Autogenerated
	}
}
